version: '2'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
    restart: always
    container_name: [REPO_NAME]
    build:
      context: .
    volumes:
      - ./[PACKAGE]:/app/[PACKAGE]
    ports:
      - "8000:8000"
